services:
  app:
    build:
      context: ./
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - "POSTGRES_DB=${PG_DB}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "54320:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
